In [20]:
import numpy as np
# Each item is one sentence so we have 7 sentence
docs = ['go pakistan',
		'pakistan pakistan',
		'hip hip hurray',
		'jeetega bhai jeetega pakistan jeetega',
		'pakistan zindabad',
		'babar azam',
		'afridi afridi']

In [21]:
#First Step is to tokenize tour data (Means if theres capital letter in sentence you have to make it im small, remove special symbols)
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')    #out of vocabluray token (Each new word will be replace by nothing )

In [22]:
tokenizer.fit_on_texts(docs)

In [23]:
tokenizer.word_index #Each unique word is tokenize by numbers

{'<nothing>': 1,
 'pakistan': 2,
 'jeetega': 3,
 'hip': 4,
 'afridi': 5,
 'go': 6,
 'hurray': 7,
 'bhai': 8,
 'zindabad': 9,
 'babar': 10,
 'azam': 11}

In [24]:
tokenizer.word_counts #Find the frequency of word

OrderedDict([('go', 1),
             ('pakistan', 5),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('zindabad', 1),
             ('babar', 1),
             ('azam', 1),
             ('afridi', 2)])

In [25]:
tokenizer.document_count # To find no of sentence

7

In [26]:
sequences = tokenizer.texts_to_sequences(docs)  # to generate sequences for text
sequences

[[6, 2], [2, 2], [4, 4, 7], [3, 8, 3, 2, 3], [2, 9], [10, 11], [5, 5]]

In [27]:
from keras.utils import pad_sequences # Because sequences are of diffent sizes

In [28]:
sequences = pad_sequences(sequences,padding='post') # so we need to apply the paddings

In [29]:
sequences

array([[ 6,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4,  7,  0,  0],
       [ 3,  8,  3,  2,  3],
       [ 2,  9,  0,  0,  0],
       [10, 11,  0,  0,  0],
       [ 5,  5,  0,  0,  0]], dtype=int32)

In [30]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [31]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [38]:
print(X_train.shape) # No of reviews in training
X_train[0] # first review

(25000, 50)


array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [33]:
len(X_train[2])

141

In [34]:
X_train = pad_sequences(X_train,padding='post',maxlen=50) # each review will be trim by 50 words to avoid long training time
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [35]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [36]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 19s 20ms/step - loss: 0.6947 - accuracy: 0.5037 - val_loss: 0.6948 - val_accuracy: 0.5056
Epoch 2/5
782/782 [==============================] - 13s 17ms/step - loss: 0.6933 - accuracy: 0.5094 - val_loss: 0.6937 - val_accuracy: 0.5048
Epoch 3/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6932 - accuracy: 0.5074 - val_loss: 0.6941 - val_accuracy: 0.5062
Epoch 4/5
782/782 [==============================] - 10s 13ms/step - loss: 0.6928 - accuracy: 0.5062 - val_loss: 0.6934 - val_accuracy: 0.5062
Epoch 5/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6929 - accuracy: 0.5076 - val_loss: 0.6938 - val_accuracy: 0.5075
